name: First DEployment Workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done -bye"
      - name: Get code
        uses: actions/checkout@v3
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print 1st deployment
        run: echo "Hello World"
      - name: Print Goodbye
        run: echo "Done -bye"
      -name: Build Project
        run: npm run build
      -name: Deploy
        run: echo "Deploying ..."
      

  
